FROM golang:1.22-alpine AS builder

RUN apk add --no-cache git

ENV CGO_ENABLED=0

WORKDIR /app

COPY . .

RUN test -f go.mod || go mod init notes && \
    go mod tidy && \
    go build -o /notes .

FROM alpine
WORKDIR /app
COPY --from=builder /notes /app/notes
COPY ui /app/ui
ENTRYPOINT ["/app/notes"]
